language: java

sudo: false
addons:
  apt:
    packages:
      - oracle-java10-installer
jdk:
  - oraclejdk10

branches:
  only:
  - master

addons:
  sonarcloud:
    organization: "doi9t-github"
script:
  # other script steps might be done before running the actual SonarQube analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar